Feat: 회원가입 로직 및 컴포넌트 추가
pp-pppp/amadda pull request #120
Opened 2023-11-08 09:50 UTC by hohee-hee

## 개요

1. 회원가입 로직 및 컴포넌트를 추가했어요.
2. 이와 관련하여 공통 컴포넌트의 ui를 일부 수정했어요.
3. `.gitkeep`을 삭제했어요.
4. 기본 카카오 버튼 및 layout에 css를 추가하였어요.

## PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [x] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [x] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2023-11-08 14:41 UTC, brewcoldblue requested changes
NextAuth 전반적으로 맡아서 하시느라 정말 고생 많으셨습니다. 몇 가지 고쳐야 할 부분들이 보이는데 아침에 이야기하면 좋을 것 같아요. 푹 주무셨으면 좋겠습니다.

2023-11-08 14:41 UTC, brewcoldblue commented on frontend/_apps/shell/components/SignUp/SignUp.tsx
> +  };
P3) 이 캡션 두 개가 정말 똑같이 생긴 걸 볼 수 있습니다. 이런 걸 컴포넌트로 빼야 해요!

2023-11-08 14:41 UTC, brewcoldblue commented on frontend/_apps/shell/components/SignUp/SignUp.tsx
> +      {nicknameCaption()}
함수형 컴포넌트를 이런 식으로 쓰는 건 좋지 못합니다. jsx 문법으로 쓸 수 있게 해 줘야 해요.

2023-11-08 14:41 UTC, brewcoldblue commented on frontend/_apps/shell/components/SignUp/SignUp.tsx
> +      {idCaption()}
여기도 마찬가지입니다.

2023-11-08 14:41 UTC, brewcoldblue commented on frontend/_apps/shell/components/SignUp/SignUp.tsx
> +      </Btn>
Form 컴포넌트를 사용하고 있지 않습니다. Form으로 감싸주세요.

2023-11-08 14:41 UTC, brewcoldblue commented on frontend/_apps/shell/hooks/useIdValidator.tsx
> +  }, []);
validate하는 부분은 구조에 대해서 한 번 더 이야기해봅시다.

2023-11-09 00:38 UTC, hohee-hee commented on frontend/_apps/shell/components/SignUp/SignUp.tsx
> +      {idCaption()}
위의 세 개 수정사항은 https://github.com/pp-pppp/amadda/pull/120/commits/b2d289ac0b3b8d4d060823bb81745c8b2c0e466f 커밋에 적용하였습니다.

2023-11-09 03:42 UTC, hohee-hee commented on frontend/_apps/shell/hooks/useIdValidator.tsx
> +  }, []);
수정 해서 커밋 올렸어요!

2023-11-09 03:53 UTC, brewcoldblue requested changes

2023-11-09 03:53 UTC, brewcoldblue commented on frontend/_apps/shell/hooks/useIdValidator.tsx
> +  }, []);
P2) 이 부분은 부적절한 것 같습니다. 초기값이 이미 false로 잘 들어가 있는데 렌더링되고 나서 한 번만 실행되도록 디펜던시 배열을 설정하셨는데 side effect 로직도 없기 때문이에요.

2023-11-09 03:53 UTC, brewcoldblue commented on frontend/_apps/shell/hooks/useIdValidator.tsx
> +    isIdEmpty: isEmpty,
P3) 요 부분은 상태 이름도 `isIdxxxx`로 통일해서 es6 문법으로 통일해주면 가독성이 더 좋아질 것 같습니다.

2023-11-09 03:53 UTC, brewcoldblue commented on frontend/_apps/shell/hooks/useNameValidator.tsx
> +        userName: nameValue,
P3) 이 부분도 불가피한 경우가 아니면 key와 value를 일치시켜주시면 좋습니다.

2023-11-09 03:53 UTC, brewcoldblue commented on frontend/_apps/shell/hooks/useNameValidator.tsx
> +    NameCheck();
P3) NameCheck 결과로 어떤 응답이 오지 않을까요? 그 값을 가지고 판단하면 될 것 같습니다.

2023-11-09 03:53 UTC, brewcoldblue commented on frontend/_apps/shell/pages/index.tsx
> +        <Spacing size="5" />{' '}
P3) 이 공백이 여기 있으면 공백 문자열이 입력되어 있게 됩니다.

2023-11-09 03:54 UTC, brewcoldblue commented on frontend/_apps/shell/hooks/useNameValidator.tsx
> +        userName: nameValue,
hook에서 return해주는 친구네요,,,, 요 부분은 취소하겠습니다.

2023-11-09 04:02 UTC, brewcoldblue commented on frontend/_apps/shell/hooks/useNameValidator.tsx
> +    NameCheck();
++ 컴포넌트가 아닌 함수의 컨벤션은 camel로 부탁드립니다

2023-11-09 04:14 UTC, brewcoldblue commented on frontend/_apps/shell/hooks/useIdValidator.tsx
> +  }, []);
다른 의도가 있으셨군요,,,,,,,,,, 이펙트 안 쓰시고 다르게 구현해보시는 걸로...

2023-11-09 04:25 UTC, brewcoldblue approved these changes
LGTM!

2023-11-09 04:25 UTC, merged