Feat: 날짜 조건으로 일정 조회 기능 구현
pp-pppp/amadda pull request #121
Opened 2023-11-08 12:40 UTC by donggeoniiii

## 개요
- 일정 조회 API에 날짜 조건으로 검색할 수 있는 기능을 추가하였습니다.
- 연별 데이터는 날짜로 검색 시 필수로 입력해야 합니다.
- 월별 데이터는 일자별 일정 조회 시 필수로 입력해야 합니다.

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2023-11-08 15:25 UTC, jeong-yeji requested changes

2023-11-08 15:25 UTC, jeong-yeji commented on backend/src/main/java/com/pppppp/amadda/schedule/controller/ScheduleController.java
> +        @RequestParam(value = "day", required = false) Optional<String> day) {
P5) 이거 int말고 string으로 받는게 더 편해서 string으로 받는건가요?

2023-11-08 15:25 UTC, jeong-yeji commented on backend/src/main/java/com/pppppp/amadda/schedule/service/ScheduleService.java
> +                        == Integer.parseInt(year);
P2) year뿐만 아니라 아래에 있는 month, year에도 해당하는 내용인데, 날짜 필터링 시 equal 비교가 아니라 포함 여부를 확인해야할 것 같아요. 예를들어 2021-01-01 ~ 2023-12-31로 설정한 일정이 있다면 2022로 검색했을 때 equal로 찾으면 검색되지 않을 것 같습니다.
`isBefore()`,` isAfter()` 메소드 사용하면 될 듯합니다. [참고](https://hianna.tistory.com/611)

2023-11-08 23:58 UTC, donggeoniiii commented on backend/src/main/java/com/pppppp/amadda/schedule/controller/ScheduleController.java
> +        @RequestParam(value = "day", required = false) Optional<String> day) {
map으로 한번에 받으려고 저렇게 했습니다.

2023-11-09 00:41 UTC, mindy0414 approved these changes

2023-11-09 04:49 UTC, jeong-yeji requested changes

2023-11-09 04:49 UTC, jeong-yeji commented on backend/src/main/java/com/pppppp/amadda/schedule/service/ScheduleService.java
> +                if (!year.isEmpty() && month.isEmpty() && day.isEmpty()) {
p5) 이거 어차피 메소드 안에 똑같은 if문 있는데 필요 없는거 아닌가요?

2023-11-09 04:49 UTC, jeong-yeji commented on backend/src/main/java/com/pppppp/amadda/schedule/service/ScheduleService.java
> +                if (!month.isEmpty() && day.isEmpty()) {
p5) 이거 어차피 메소드 안에 똑같은 if문 있는데 필요 없는거 아닌가요?

2023-11-09 04:49 UTC, jeong-yeji commented on backend/src/main/java/com/pppppp/amadda/schedule/service/ScheduleService.java
> +                .atTime(23, 59, 59))
p1) 이거... 돌아가는거 맞나요 변수로 몇번 빼봤는데 괄호 수가 안맞다고 나와요

2023-11-09 04:54 UTC, jeong-yeji approved these changes

2023-11-09 04:55 UTC, merged