Feature/schedule mobile calendar
pp-pppp/amadda pull request #207
Opened 2023-11-17 06:36 UTC by hohee-hee

## 개요
### 📅 캘린더의 메인 페이지를 만들었어요.
1. external-temporal에서 구현된 컴포넌트 중 일부의 타입과 css를 수정했어요.
2. 미리 만들어두었던 schedule 내부 컴포넌트도 합치는 과정에 맞게 일부 로직과 css를 수정했어요.
3. hooks 내부에는 캘린더에 날짜를 만들어주는 hook과 `/schedule/server-time`에서 response를 받아오는 hook이 있어요.
4. index에 들어가기 위하여 `MobileMain`컴포넌트에 조립했어요.
- 페이지는 두 개로 나누어져 있습니다. 캘린더뷰와 날짜가 확정된 일정을 보여주는 `MobileMonthlyPage`와 `MobileUnscheduledPage`로 구성되어있어요. `MobileMonthlyPage`의 하위 컴포넌트로는 연월과 오늘로 가는 버튼, 카테고리 선택 필터를 갖고 있는 `CalendarHeader`와 특정 날짜의 일정리스트인 `DailyList`가 있어요. 실제 조립 과정에서는 그 사이에 캘린더 컴포넌트를 넣었습니다.

## PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [x] CSS 등 사용자 UI 디자인 변경
- [x] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2023-11-18 04:19 UTC, brewcoldblue requested changes

2023-11-18 04:19 UTC, brewcoldblue commented on frontend/_apps/schedule/components/MobileDailyPlate/MobileDailyPlate.css.ts
> +  display: '-webkit-box',
P4) 이거는 추후에 다른 방식으로 수정해야할 것 같아요. deprecated 된 문법이고, webkit 기반이 아닌 브라우저에서 제대로 작동하지 않을 수 있습니다. 표준 옵션이 아니에요! (웹뷰 전제여서 더 치명적일 수 있어요.) 마감이 월요일이어서 일단 P4로 달아둡니다.

2023-11-18 04:19 UTC, brewcoldblue commented on frontend/_apps/schedule/components/MobileMain/MobileMain.tsx
> +        pages={[MobileMonthlyPage(), MobileUnscheduledPage()]}
P3) JSX 컴포넌트 문법으로 넣어주세요! titles도 상수변수로 빼 주시면 좋겠습니다.

2023-11-18 04:19 UTC, brewcoldblue commented on frontend/_apps/schedule/components/MobileMain/MobileMonthlyPage/CalendarHeader/CalendarHeader.tsx
> +          오늘
P3) 상수변수!!!

2023-11-18 04:19 UTC, brewcoldblue commented on frontend/_apps/schedule/components/MobileMain/MobileMonthlyPage/DailyList/DailyList.tsx
> +  };
P2) 더미 삭제하고, API 연결해주세요.

2023-11-18 04:19 UTC, brewcoldblue commented on frontend/_apps/schedule/components/MobileMain/MobileMonthlyPage/DailyList/DailyList.tsx
> +          <Span color="grey">일정이 없어요.</Span>
이 부분도 상수변수!

2023-11-18 04:19 UTC, brewcoldblue commented on frontend/_apps/schedule/components/MobileMain/MobileUnscheduledPage/MobileUnscheduledPage.tsx
> +      </MobileDailyPlateList>
P2) 이 컴포넌트 더미도 모두 삭제해주시고 데이터와 연결해주세요!! ㅋㅋㅋ

2023-11-18 04:56 UTC, hohee-hee commented on frontend/_apps/schedule/components/MobileDailyPlate/MobileDailyPlate.css.ts
> +  display: '-webkit-box',
리팩 기간에 다시 한 번 손을 보도록 하겠습니다!

2023-11-18 13:52 UTC, brewcoldblue requested changes
정신을 차려봅시다,,, 실제 데이터 뿌려주는 코드로 고쳐주세요. 위에 누락된 것도 하나 있습니다

2023-11-18 13:52 UTC, brewcoldblue commented on frontend/_apps/schedule/components/MobileCalendar/MobileCalendarDate/MobileCalendarDate.tsx
> +        <React.Fragment key={rowIndex}>
P4) 그냥 div 쓰셔도 됩니다,,,,

2023-11-18 13:52 UTC, brewcoldblue commented on frontend/_apps/schedule/components/MobileMain/MobileMonthlyPage/CalendarHeader/CalendarHeader.tsx
> +            업무
P1) 실제 데이터 들어올 수 있게 고쳐주세용

2023-11-19 08:24 UTC, brewcoldblue approved these changes
고생하셨습니다. 리뷰 두 개는 구두로도 말씀드렸으니 고치시고 머지하시면 될 것 같아요.

2023-11-19 08:24 UTC, brewcoldblue commented on frontend/_apps/schedule/components/MobileMain/MobileMonthlyPage/MobileMonthlyPage.tsx
> +import { Spacing } from '../../../../../_packages/@external-temporal';
P3) 로컬 임포트 말고 의존성 임포트 해주세요!

2023-11-19 08:24 UTC, brewcoldblue commented on frontend/_apps/schedule/components/MobileMain/MobileMonthlyPage/MobileMonthlyPage.tsx
> +  }, [ref]);
P3) ref나 ref.current를 디펜던시에 집어넣는 것은 아무 의미가 없습니다. React에 의해 리렌더링이 추적되지 않기 때문인데요, 이 경우에는 페이지 렌더 시 한 번만 이벤트 리스너를 달아주면 되므로 빈 배열로 두시면 됩니다.

2023-11-19 08:50 UTC, merged