Chore: module federation 병합
pp-pppp/amadda pull request #296
Opened 2024-03-07 13:22 UTC by brewcoldblue

## 개요

- 쪼개져있던 4개의 Next.js App을 `Shell`로 병합합니다.
- module federation plugin 이슈가 너무 자주 발생하여, 해당 스택을 포기하고 하나의 Next App으로 병합해 개발한 후 도메인을 쪼개는 방향으로 토론하였습니다.
- App을 합치면서 모든 디렉토리 및 파일명에 케밥 케이스를 적용했습니다. (API 동적 라우트는 `[user_seq]` 처럼 언더바를 사용합니다)

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [x] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-08 12:36 UTC, 0minyoung0 approved these changes

2024-03-08 13:34 UTC, hohee-hee requested changes

2024-03-08 13:34 UTC, hohee-hee commented on frontend/apps/shell/pages/api/schedule/[schedule_seq]/participation.ts
> +      const { code, message, data } = await https.delete(`${process.env.SPRING_API_ROOT}/schedule/${scheduleSeq}/participation`, token);
P1) `${scheduleSeq}`를 `${schedule_seq}`로 변경해주세요.

2024-03-08 13:34 UTC, hohee-hee commented on frontend/apps/shell/utils/schedule/convertFormData.ts
> +import type { ScheduleEditFormData } from '@/components/ScheduleEdit/ScheduleEditForm/formdata';
P1) `'@/components/schedule-edit/schedule-edit-form/formdata'`로 경로 수정해주세요.

2024-03-08 13:34 UTC, hohee-hee commented on frontend/apps/shell/utils/schedule/validators/scheduleValidator.ts
> +import { ScheduleEditFormData } from '../../components/ScheduleEdit/ScheduleEditForm/formdata';
P1) `'@/components/schedule-edit/schedule-edit-form/formdata'`로 경로 수정해주세요.

2024-03-09 08:36 UTC, brewcoldblue commented on frontend/apps/shell/utils/schedule/validators/scheduleValidator.ts
> +import { ScheduleEditFormData } from '../../components/ScheduleEdit/ScheduleEditForm/formdata';
일부 파일들의 임포트 수정이 저장이 안 된 채로 커밋된 것 같습니다. 일괄적으로 수정한 것이어서 수정되면서 동시에 저장되는데 누락되었네요...

2024-03-09 12:27 UTC, hohee-hee approved these changes
고생하셨습니다!

2024-03-09 13:58 UTC, merged